openapi: 3.0.3
info:
  title: Expenses API
  description: API de suivi des dépenses
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths: {}
components:
  schemas:
    Expense:
      type: object
      required:
        - label
        - amount
        - date
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        label:
          type: string
          maxLength: 255
        amount:
          type: number
          format: double
          minimum: 0
        date:
          type: string
          format: date
